# Generated by Django 4.1 on 2022-09-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('is_delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('price', models.IntegerField()),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(db_index=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_active', models.BooleanField()),
                ('is_delete', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand')),
                ('category', models.ManyToManyField(to='product_module.productcategory')),
            ],
        ),
    ]
