# Generated by Django 4.1 on 2022-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='is_delete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
