# Generated by Django 4.1 on 2022-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_productcomment_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvisit',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
