# Generated by Django 4.1 on 2022-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_productvisit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productcategory'),
        ),
    ]
