# Generated by Django 4.1 on 2022-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_productbrand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productbrand'),
        ),
    ]
