# Generated by Django 4.1 on 2022-09-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_remove_productbrand_category_productcategory_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='brand',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productcategory'),
        ),
    ]
