# Generated by Django 4.1 on 2022-09-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sliders'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=400)),
                ('footer_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footerbox')),
            ],
        ),
    ]
