# Generated by Django 4.1 on 2022-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_footerbox_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
