# Generated by Django 4.1 on 2022-09-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_footerlink_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='is_active',
        ),
    ]
