# Generated by Django 4.1 on 2022-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_remove_user_addresses_address_address_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
