# Generated by Django 4.1 on 2022-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_adminmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='text',
            field=models.TextField(),
        ),
    ]
