# Generated by Django 4.1 on 2022-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_alter_adminmessages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
