# Generated by Django 4.1 on 2022-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_alter_adminmessages_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
